import { Express } from 'express';
import authRoutes from './domains/auth/routes';
import healthRoutes from './domains/health/routes';
import paymentsRoutes from './domains/payments/routes';
import automationsRoutes from './domains/automations/routes';
import automationRoutes from './domains/automation/routes';
import notificationsRoutes from './domains/notifications/routes';
import billingRoutes from './domains/billing/routes';
import customersRoutes from './domains/customers/routes';
import coverageRoutes from './domains/coverage/routes';
import dashboardRoutes from './domains/dashboard/routes';
import gisRoutes from './domains/gis/routes';
import provisioningRoutes from './domains/provisioning/routes';
import inventoryRoutes from './domains/inventory/routes';
import inventorySyncRoutes from './domains/inventory-sync/routes';
import ipamRoutes from './domains/ipam/routes';
import manualSafeModeRoutes from './domains/manual-safe-mode/routes';
import mikrotikRoutes from './domains/mikrotik/routes';
import networkRoutes from './domains/network/routes';
import nocRoutes from './domains/noc/routes';
import nocTelemetryRoutes from './domains/noc-telemetry/routes';
import nocPollerRoutes from './domains/noc-poller/routes';
import plansRoutes from './domains/plans/routes';
import reportsRoutes from './domains/reports/routes';
import routerosReadOnlyRoutes from './domains/routeros-readonly/routes';
import routerosResourcesRoutes from './domains/routeros-resources/routes';
import routerosTemplatesRoutes from './domains/routeros-templates/routes';
import routerTemplateParametersRoutes from './domains/router-template-parameters/routes';
import routerEnrollmentRoutes from './domains/router-enrollment/routes';
import safeCommandQueueRoutes from './domains/safe-command-queue/routes';
import securityRoutes from './domains/security/routes';
import serviceStatusRoutes from './domains/service-status/routes';
import suspensionRoutes from './domains/suspension/routes';
import systemRoutes from './domains/system/routes';
import ticketsRoutes from './domains/tickets/routes';
import wireguardRoutes from './domains/wireguard/routes';

export function registerRoutes(app: Express): void {
  app.use(healthRoutes);
  app.use(authRoutes);
  app.use(customersRoutes);
  app.use(coverageRoutes);
  app.use(plansRoutes);
  app.use(billingRoutes);
  app.use(reportsRoutes);
  app.use(automationsRoutes);
  app.use(automationRoutes);
  app.use(notificationsRoutes);
  app.use(securityRoutes);
  app.use(serviceStatusRoutes);
  app.use(provisioningRoutes);
  app.use(suspensionRoutes);
  app.use(systemRoutes);
  app.use(networkRoutes);
  app.use(mikrotikRoutes);
  app.use(wireguardRoutes);
  app.use(routerosReadOnlyRoutes);
  app.use(routerosResourcesRoutes);
  app.use(routerosTemplatesRoutes);
  app.use(routerTemplateParametersRoutes);
  app.use(routerEnrollmentRoutes);
  app.use(ticketsRoutes);
  app.use(inventoryRoutes);
  app.use(inventorySyncRoutes);
  app.use(ipamRoutes);
  app.use(nocRoutes);
  app.use(nocTelemetryRoutes);
  app.use(nocPollerRoutes);
  app.use(manualSafeModeRoutes);
  app.use(safeCommandQueueRoutes);
  app.use(gisRoutes);
  app.use(dashboardRoutes);
  app.use(paymentsRoutes);
}
