import { Express } from 'express';
import authRoutes from './domains/auth/routes';
import healthRoutes from './domains/health/routes';
import paymentsRoutes from './domains/payments/routes';
import automationsRoutes from './domains/automations/routes';
import automationRoutes from './domains/automation/routes';
import notificationsRoutes from './domains/notifications/routes';
import billingRoutes from './domains/billing/routes';
import customersRoutes from './domains/customers/routes';
import coverageRoutes from './domains/coverage/routes';
import dashboardRoutes from './domains/dashboard/routes';
import gisRoutes from './domains/gis/routes';
import provisioningRoutes from './domains/provisioning/routes';
import inventoryRoutes from './domains/inventory/routes';
import inventorySyncRoutes from './domains/inventory-sync/routes';
import ipamRoutes from './domains/ipam/routes';
import manualSafeModeRoutes from './domains/manual-safe-mode/routes';
import mikrotikRoutes from './domains/mikrotik/routes';
import networkRoutes from './domains/network/routes';
import oltRoutes from './domains/olt/routes';
import nocRoutes from './domains/noc/routes';
import nocTelemetryRoutes from './domains/noc-telemetry/routes';
import nocPollerRoutes from './domains/noc-poller/routes';
import snmpPollerRoutes from './domains/snmp-poller/routes';
import plansRoutes from './domains/plans/routes';
import reportsRoutes from './domains/reports/routes';
import routerosReadOnlyRoutes from './domains/routeros-readonly/routes';
import routerosResourcesRoutes from './domains/routeros-resources/routes';
import routerosTemplatesRoutes from './domains/routeros-templates/routes';
import routerTemplateParametersRoutes from './domains/router-template-parameters/routes';
import routerEnrollmentRoutes from './domains/router-enrollment/routes';
import safeCommandQueueRoutes from './domains/safe-command-queue/routes';
import securityRoutes from './domains/security/routes';
import serviceStatusRoutes from './domains/service-status/routes';
import suspensionRoutes from './domains/suspension/routes';
import systemRoutes from './domains/system/routes';
import ticketsRoutes from './domains/tickets/routes';
import wireguardRoutes from './domains/wireguard/routes';
import commercialRoutes from './domains/commercial/routes';
import clientActionsRoutes from './domains/client-actions/routes';
import financeOperationalRoutes from './domains/finance-operational/routes';
import purchasesRoutes from './domains/purchases/routes';
import client360Routes from './domains/client-360/routes';
import collectionsRoutes from './domains/collections/routes';
import portalRoutes from './domains/portal/routes';
import routerConfigAuditRoutes from './domains/router-config-audit/routes';
import radiusRoutes from './domains/radius/routes';
import tenancyRoutes from './domains/tenancy/routes';
import wispOnboardingRoutes from './domains/wisp-onboarding/routes';
import integrationsRoutes from './domains/integrations/routes';
import jobsRoutes from './domains/jobs/routes';
import contractTemplateRoutes from './domains/contract-templates/routes';
import contractRoutes from './domains/contracts/routes';

export function registerRoutes(app: Express): void {
  app.use(healthRoutes);
  app.use(authRoutes);
  app.use(customersRoutes);
  app.use(coverageRoutes);
  app.use(plansRoutes);
  app.use(billingRoutes);
  app.use(reportsRoutes);
  app.use(automationsRoutes);
  app.use(automationRoutes);
  app.use(notificationsRoutes);
  app.use(securityRoutes);
  app.use(serviceStatusRoutes);
  app.use(provisioningRoutes);
  app.use(suspensionRoutes);
  app.use(systemRoutes);
  app.use(networkRoutes);
  app.use(oltRoutes);
  app.use(mikrotikRoutes);
  app.use(wireguardRoutes);
  app.use(routerosReadOnlyRoutes);
  app.use(routerosResourcesRoutes);
  app.use(routerosTemplatesRoutes);
  app.use(routerTemplateParametersRoutes);
  app.use(routerEnrollmentRoutes);
  app.use(ticketsRoutes);
  app.use(inventoryRoutes);
  app.use(inventorySyncRoutes);
  app.use(ipamRoutes);
  app.use(nocRoutes);
  app.use(nocTelemetryRoutes);
  app.use(nocPollerRoutes);
  app.use(snmpPollerRoutes);
  app.use(manualSafeModeRoutes);
  app.use(safeCommandQueueRoutes);
  app.use(gisRoutes);
  app.use(dashboardRoutes);
  app.use(paymentsRoutes);
  app.use(commercialRoutes);
  app.use(purchasesRoutes);
  app.use(financeOperationalRoutes);
  app.use(integrationsRoutes);
  app.use(clientActionsRoutes);
  app.use(client360Routes);
  app.use(collectionsRoutes);
  app.use(portalRoutes);
  app.use(routerConfigAuditRoutes);
  app.use(radiusRoutes);
  app.use(tenancyRoutes);
  app.use(wispOnboardingRoutes);
  app.use(jobsRoutes);
  app.use(contractTemplateRoutes);
  app.use(contractRoutes);
}
